name: dumbdumb_flutter_app
description: My dumbdumb Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  provider: ^6.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # System/Structure
  go_router: ^10.1.2
  flutter_lints: ^2.0.2

  # Device Info
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  store_redirect: ^2.0.1
  permission_handler: ^10.4.1
  flutter_jailbreak_detection: ^1.10.0
  connectivity_plus: ^4.0.1

  # Data
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  file: ^6.1.4

  # Firebase
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.6.4
  firebase_crashlytics: ^3.3.3
  firebase_remote_config: ^4.2.3

  # Push Notification
  flutter_local_notifications: ^15.0.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
